### ISSUE TITLE
Incomplete metadata obtained 

### ISSUE THREAD

**Issue by Chengwei94** [pachterlab/ffq#24]
Hi there, I think that this tool is great and really useful for the community. However, it does sometimes does not return the complete information or incorrect information. 

I think one example is this 

`
ffq SRS5634098
`
which returns
 
[2022-05-26 16:47:06,659]    INFO Parsing sample SRS5634098
[2022-05-26 16:47:07,699] WARNING No experiment found
[2022-05-26 16:47:07,699]    INFO Getting Experiment for SRS5634098
[2022-05-26 16:47:07,699] WARNING No Experiment found for SRS5634098
{
    "SRS5634098": {
        "accession": "SRS5634098",
        "title": "GM12878 3T3 species mixing mouse (RNA-Seq)",
        "organism": "Mus musculus",
        "attributes": {
            "source_name": "GM12878 3T3 species mixing",
            "strain": "none",
            "ENA-FIRST-PUBLIC": "2020-10-24",
            "ENA-LAST-UPDATE": "2020-10-24"
        },
        "experiments": ""

However, from the ncbi link we can see that there are experiments that come with it. 
https://www.ncbi.nlm.nih.gov/sra?term=SRX7124455 

Edit: Seems that https://www.ebi.ac.uk/ena/browser/api/xml/SRS5634098 is different from ncbi resulting in this

**Comment by agalvezm** [comment]
Hello Chengwei 94! Thanks for the nice words and for bringing this to our attention. As you point out, the ENA API (which ffq uses for fetching SRA samples) has incomplete information for SRS5634098, and does not include any experiment for that accession while NCBI does. Therefore, we have improved fetching so that, when the ENA API does not return any experiment, we confirm this is correct with the NCBI API. If NCBI does contain experiment ids, then ffq will return the metadata for those.

These changes have been added to the `devel` branch, and will be merged with master for the next release. In the meantime, if you wish to test out the new functionality, you can install the development version by running:

`pip install git+https://github.com/pachterlab/ffq@devel`
