### ISSUE TITLE
Network unreachable behind proxy

### ISSUE THREAD

**Issue by karl-az** [pachterlab/ffq#27]
Trying to run an example given in the README I get an error:

```bash
$ ffq GSE129845
[2022-06-22 10:45:15,161]    INFO Parsing GEO GSE129845
[2022-06-22 10:45:15,908]    INFO Finding supplementary files for GEO GSE129845
[2022-06-22 10:49:32,108]   ERROR [Errno 101] Network is unreachable
{}
```

I traced it back here:
https://github.com/pachterlab/ffq/blob/master/ffq/utils.py#L727

I have standard proxy variables like (FTP_PROXY/ftp_proxy) configured and I can access ftp.ncbi.nlm.nih.gov with for instance lftp.

Looking at the config file I realized the other repositories use https rather than ftp. Using SRP192646 rather than GSE129845 works.

Still is there a way to make the ftp part of ffq aware of proxy settings?

**Comment by karl-az** [comment]
@sbooeshaghi how would you prefer to have issues reported? Is there a better way than opening issues here?

**Comment by sbooeshaghi** [comment]
Hi @karl-az, apologies for the delayed reply. Issues are the best way to address problems with `ffq`. I'm not exactly sure what changes on our end would help resolve this issue as I don't know much about setting up and using proxy variables. Did you have any suggested changes you could make in a pull request that would resolve this issue?

**Comment by karl-az** [comment]
Thank you for answering. We all have our own schedules to adjust to.

I am no expert either, but I can see a couple of options. I will try to find time to implement it, but in the meantime, I'll share my thoughts here.
* Add proxy settings to the connection step as, for instance, suggested here: https://stackoverflow.com/questions/47167538/connecting-with-ftplib-via-ftp-proxy-in-python. Either:
  * expose proxy and proxy port as optional arguments on the command line
  * read the environment variable ftp_proxy/FTP_PROXY (https://www.gnu.org/software/wget/manual/html_node/Proxies.html). This variable is sometimes set as ftp_proxy and sometimes as FTP_PROXY. Best would be to try and read both and if it exists, inject it in the connection step
* Another alternative would be to download the data from a http mirror. I'm not sure if GEO provides that though.

The easiest to implement would be to check for the proxy-variables. I would lean towards that if I'd provide a PR.

**Comment by sbooeshaghi** [comment]
Thank you for taking the time to explain the issue; I think I understand the problem a bit better now. So it seems like because you are using an FTP proxy you need to be able to pass the proxy and proxy port (or read them in from FTP_PROXY or ftp_proxy env variables) so that you can get the GEO supplementary files from FTP.

As this would enhance the usage of `ffq` I've labeled this feature as an enhancement. If you are able to add this functionality (and unit test) and submit a PR then we can get it added to a future release! I think starting with hidden cli options to pass the proxy and proxy port would be a good first start and future enhancements can also check for the environmental variables. What do you think?

**Comment by karl-az** [comment]
Exactly.

For someone external it would probably be easier to implement it the other way around as you would only need to update the ftp-method to add environment variables. To add the cli option you need a more complete overview.

I would come back to this discussion when I find time to do the work.

**Comment by sbooeshaghi** [comment]
Ok- thank you for the tip that all sounds great.
