### ISSUE TITLE
aws example no longer works

### ISSUE THREAD

**Issue by gordonaa** [pachterlab/ffq#32]
Thanks for the great tool!

Running the example from the readme to retrieve the AWS data worked on July 5th, 2022 but didn't work on the next day (July 6th):
```
$ ffq --aws SRX7347523
[2022-07-06 12:15:44,487]    INFO Parsing Experiment SRX7347523
[2022-07-06 12:15:44,993] WARNING There is 1 run for SRX7347523
[2022-07-06 12:15:44,993]    INFO Parsing run SRR10668798
[]
```
I additionally tried on a number of other IDs but none worked

**Comment by cartographerJ** [comment]
Same thing for google -- it seems like cloud links are no longer being fetched.

**Comment by cartographerJ** [comment]
Annoyingly, it seems like NCBI has completely removed the links to fastq files from their databases and the run selectors so we are stuck with .sra files.

**Comment by sbooeshaghi** [comment]
As it turns out, it seems like (based on numerous API requests) NCBI has started phasing out `.sra` files for many accessions. Since there are presumably some accessions for which the `.sra` file is still accessible we will keep the `--ncbi` option in the next release of `ffq` but will continue to monitor the situation to see if things change.
