### ISSUE TITLE
Fetching metadata from NCBI

### ISSUE THREAD

**Issue by Sorcery229** [pachterlab/ffq#50]
Hi!
Thank you for your hard work put into creating this tool. It's great! I've tried to use it to retrieve some metadata information from NCBI for this accession number **GSE130033**. My goal is to retrieve each sample's characteristics such as sample type, sex and age.
I tried to run
 `ffq GSE130033` 
and it failed with a following error
`CalledProcessError: Command 'b'ffq GSE130033\n'' returned non-zero exit status 2.`
Then I tried to run
`ffq -l 2 GSE130033`
and I managed to get some information, but there is no metadata I need. If I try set a number greater than 2 it fails with an error as well. My question is whether my output is correct or I am missing something. Thank you!

**Comment by agalvezm** [comment]
Thanks so much for using ffq!

If I run the command you provide, I get the following more informative error message:

> $ ffq GSE130033
> 
> [2022-10-10 15:59:21,742]    INFO Parsing GEO GSE130033
> 
> [2022-10-10 15:59:22,190]    INFO Finding supplementary files for GEO GSE130033
> 
> [2022-10-10 15:59:25,272] WARNING There are 6 samples for GSE130033
> 
> [2022-10-10 15:59:25,273]    INFO Parsing GSM GSM3730462
> 
> [2022-10-10 15:59:25,910]    INFO Finding supplementary files for GSM GSM3730462
> 
> [2022-10-10 15:59:28,436]    INFO Getting sample for GSM3730462
> 
> **[2022-10-10 15:59:28,888] WARNING No sample found. Either the provided GSM accession is invalid or raw data was not provided for this record**


You are getting this error because there are no SRA samples (SRS) associate with the GSMs of GSE130033. By default, ffq traverses the GEO and SRA databases down to the SRR accession, which contains the raw fastq download links. Since the GSMs of GSE130033 do not have any associated SRA accession (see the [GEO website for GSM3730462](GSM3730462) for example), ffq fails and exit.

Unfortunately, this means that the metadata you are looking for has not been uploaded and, as you point out, using the`-l` option is the only way of obtaining the limited metadata available.

Hope this helps!
