### ISSUE TITLE
feature request: return metadata when no fastq available 

### ISSUE THREAD

**Issue by crazyhottommy** [pachterlab/ffq#51]
Hi, Thanks for this great tool. 
If you can add the functionality to return metadata even if the raw fastqs are not provided on GEO, that will be great.
![image](https://user-images.githubusercontent.com/4106146/191329772-f667da14-99e2-457c-9ae8-6e2aaee8f87c.png)

Thanks!

**Comment by agalvezm** [comment]
Thanks so much for using ffq! 

You are getting this error because there is no SRA accession associate with that GSM. By default, ffq traverses the GEO and SRA databases down to the SRR accession, which contains the raw fastq download links. Since GSM5188367 does not have any associated SRA accession (see [GEO website](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5188367)), ffq fails and exit.

A way around this is to specify the level at which you want ffq to stop retriving metadata. For example, if you are just interested in the metadata for GSM5188367, you can type:
`ffq GSM5188367 -l 1
`
Which returns:

```
{
    "GSM5188367": {
        "accession": "GSM5188367",
        "geo_id": "305188367",
        "platform": {
            "accession": "GPL20795",
            "title": "HiSeq X Ten (Homo sapiens)"
        }
    }
}
```
If you wanted to get the metadata for all GSM associated with GSE169246, you can type:

`ffq GSE169246 -l 2`

Hope this helps!
