### ISSUE TITLE
No sample found for any GEO entries

### ISSUE THREAD

**Issue by NaotoKubota** [pachterlab/ffq#65]
Hi, I report that ffq was not able to fetch fastq URL for any GEO entries right now.

For example, I tried to download metadata for `GSE66230` like this:
```bash
ffq --verbose GSE66230 -o ./
```
The log says like `ERROR 404 Client Error:  for url: https://www.ebi.ac.uk/ena/browser/api/xml/SRX886447/` and `WARNING No sample found` for any samples.
I tried other entries many times and got the same error each time.
It looks problems of ~~GEO~~ ENA side but just in case I report this here.

Thanks,

**Comment by hazirliver** [comment]
Hi there,

I am encountering the same issue as reported. I also receive a 404 Client Error when attempting to fetch URLs for various entries, indicating a possible issue with EMBL's server.

Does anyone know the appropriate contact or procedure to request a server check or reboot on EMBL's side?

Thank you

**Comment by hazirliver** [comment]
Hello everyone,

I've investigated the errors we've been encountering with fetching data for GEO entries and found that the issue seems to stem from the URL format used in the get_xml function within ffq/utils.py. Specifically, the API requests were failing due to a trailing slash at the end of the ENA URL.

By removing this trailing slash from the URL, I was able to successfully fetch data without encountering the 404 Client Error. This modification allows proper URL formation and aligns with the updated API requirements of ENA.

I have submitted a Pull Request to address this issue: [Fix: Remove trailing slash from ENA URL in get_xml #66](https://github.com/pachterlab/ffq/pull/66). If merged, this should resolve the 'No sample found for any GEO entries' error by ensuring correct data retrieval from the ENA database.

**Comment by sbooeshaghi** [comment]
Thank you @hazirliver for your contributions. I have incorporated your bug fix into the ffq codebase and have updated the package on GitHub and on pip. These examples should now work.

https://pypi.org/project/ffq/0.3.1/

Thank you all again.
